#!/bin/sh
JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Versions/1.6.0/Home

$JAVA_HOME/bin/java -classpath build/oo-kv-storage.jar:lib/args4j-2.0.8.jar:lib/commons-codec-1.3.jar:lib/commons-httpclient-3.1.jar:lib/commons-logging-1.1.jar:lib/commons-pool-1.4.jar:lib/jsdk-24.jar:lib/junit-4.0.jar:lib/libthrift-svn-r761389.jar:lib/log4j-1.2.15.jar:lib/netty-3.0.2.GA.jar:lib/oscache-2.4.1.jar:lib/slf4j-api-1.5.6.jar:lib/slf4j-log4j12-1.5.6.jar:lib/spring-2.5.6.jar:lib/spy-memcached-2.3.jar:lib/tokyotyrant-0.6.2.jar com.othersonline.kv.server.main.SimpleThriftServer $@
